[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ion_md"
version = "0.1.0"
description = "Packmol + LAMMPS jobflow workflows for lutathera solvation md"
requires-python = ">=3.10"
dependencies = [
    "jobflow",
]

[tool.setuptools.packages.find]
include = ["drug__md*"]
